import { Injectable } from '@angular/core';
import { PlanningData } from './planningData';


export interface FieldsElement {
  name: string;
  title : string;
  position: number;
  prompt: string;
  isDayField: boolean;
  hideField: boolean;
  sticky: boolean;
  style: {};
}

const listGridFields: FieldsElement[] = [
  {position: 1, name: 'ZY78IDAFFA_Label', title:'PA', prompt: 'Position d&rsquo;Activités au premier jour du planning affiché', sticky: true, isDayField: false, hideField: false, style: {'width':'100px', 'height' : '22px', 'align':'center'}},
  {position: 2, name: 'ZEYDTYPEPA_Label', title:'Type', prompt: 'Type de la Position d&rsquo;Activités', sticky: true, isDayField: false, hideField: false, style: {'width':'70px', 'height' : '22px', 'align':'center'}},
  {position: 3, name: 'ZY3YNMPRES', title:'Nom prénom', prompt: 'Nom de l&rsquo;agent', sticky: true, isDayField: false, hideField: false, style: {'width':'150px', 'height' : '22px', 'align':'center'}},
  {position: 4, name: 'ZY00MATCLE', title:'IDRH', prompt: 'IDRH de l&rsquo;agent"', sticky: true, isDayField: false, hideField: false, style: {'width':'70px', 'height' : '22px', 'align':'center'}},
  {position: 5, name: 'ZYYFIDSF_LABEL', title:'Savoir-faire', prompt: 'Savoir-faire', sticky: true, isDayField: false, hideField: false, style: {'width':'70px', 'height' : '22px', 'align':'center'}},
  {position: 6, name: 'ZYCOTYPCON_Label', title:'Type de contrat', prompt: 'Type de la Position d&rsquo;Activités', sticky: true, isDayField: false, hideField: false, style: {'width':'150px', 'height' : '22px', 'align':'center'}},
  {position: 7, name: 'ZEYDMETIER_Label', title:'Métier PA', prompt: 'Métier de la PA"', sticky: true, isDayField: false, hideField: false, style: {'width':'150px', 'height' : '22px', 'align':'center'}},
  {position: 8, name: 'TEAM_LABEL', title:'Equipe', prompt: 'Equipe', sticky: true, isDayField: false, hideField: false, style: {'width':'150px', 'height' : '22px', 'align':'center'}},
  {position: 9, name: 'TEAM_PARENT_LABEL', title:'Niveaux parents', prompt: 'Niveaux parents', sticky: true, isDayField: false, hideField: false, style: {'width':'150px', 'height' : '22px', 'align':'center'}},
  {position: 22, name: 'DAY_20220301', title:'Mer 01', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 11, name: 'DAY_20220302', title:'Jeu 02', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 12, name: 'DAY_20220303', title:'Ven 03', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 13, name: 'DAY_20220304', title:'Sam 04', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 14, name: 'DAY_20220305', title:'Dim 05', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 15, name: 'DAY_20220306', title:'Lun 06', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 16, name: 'DAY_20220307', title:'Mar 07', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 17, name: 'DAY_20220308', title:'Mer 08', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 18, name: 'DAY_20220309', title:'Jeu 09', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 19, name: 'DAY_20220310', title:'Ven 10', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 20, name: 'DAY_20220311', title:'Sam 11', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 21, name: 'DAY_20220312', title:'Dim 12', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 22, name: 'DAY_20220313', title:'Lun 13', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 23, name: 'DAY_20220314', title:'Mar 14', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 24, name: 'DAY_20220315', title:'Mer 15', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 25, name: 'DAY_20220316', title:'Jeu 16', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 26, name: 'DAY_20220317', title:'Ven 17', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 27, name: 'DAY_20220318', title:'Sam 18', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 28, name: 'DAY_20220319', title:'Dim 19', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 29, name: 'DAY_20220320', title:'Lun 20', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 30, name: 'DAY_20220321', title:'Mar 21', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 31, name: 'DAY_20220322', title:'Mer 22', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 32, name: 'DAY_20220323', title:'Jeu 23', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 33, name: 'DAY_20220324', title:'Ven 24', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 34, name: 'DAY_20220325', title:'Sam 25', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 35, name: 'DAY_20220326', title:'Dim 26', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 36, name: 'DAY_20220327', title:'Lun 27', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 37, name: 'DAY_20220328', title:'Mar 28', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 38, name: 'DAY_20220329', title:'Mer 29', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 39, name: 'DAY_20220330', title:'Jeu 30', prompt: '', sticky: false, isDayField: true, hideField: false, style: {'width':'30px', 'height' : '22px', 'align':'center'}},
  {position: 41, name: 'COUNTER_SECABILITY', title:'Secabilite', prompt: '', sticky: false, isDayField: false, hideField: false, style: {'width':'70px', 'height' : '22px', 'align':'center'}},
  {position: 41, name: 'COUNTER_FORECAST_ABSENCES', title:'absence inopine', prompt: '', sticky: false, isDayField: false, hideField: false, style: {'width':'70px', 'height' : '22px', 'align':'center'}},
  
];


const dataElement = [
  { 'TEAM_CODE': "14078058", 'TEAM_LABEL': "CODIR (BAYEUX PDC1 > (HRLCD) BAYEUX PDC1)", 'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC1", 'ZY78IDAFFA_Label': 'PA1', 'ZEYDTYPEPA_Label': 'Type de la Position', 'ZY3YNMPRES': 'NOM32 PREN32', 'ZY00MATCLE': 'MAT032',
  "FULL_STYLEDAY_20220301": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220302": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220303": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220304": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220305": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220306": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220307": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220308": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220309": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220310": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220311": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220312": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220313": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220314": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220315": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220316": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220317": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220318": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220319": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220320": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220321": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220322": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220323": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220324": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220325": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220326": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220327": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220328": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220329": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  "FULL_STYLEDAY_20220330": "{background-image:url(../../assets/images/icons/GA_FORECAST_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
  
   isGroup: true },
  {
      'TEAM_CODE': "14078059",
      'TEAM_LABEL': "CODIR (BAYEUX PDC1 > (HRLCD) BAYEUX PDC1)",
      'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC1",
      'ZEYDMETIER_Label': "MANAGER EXPLOITATION",
      'ZEYDMETIER_Sort': 9999,
      'ZEYDTYPEPA_Label': "PTNR",
      'ZY00MATCLE': "RWL495",
      'ZY00SOCCLE': "LPC",
      'ZY3YNMPRES': "RWLNOM RWLPRENOM",
      'ZY54TEMVHI': false,
      'ZY78IDAFFA': "140780ES",
      'ZY78IDAFFA_Label': "CE2 DO",
      'ZYCOTYPCON_Label': "CDI droit privé",
      'DAY_20220304': 'PA1',
      'DAY_20220305': 'CA',
      'DAY_20220306': 'CA',
      'DAY_20220307': 'CA',
      'DAY_20220308': 'CA',
      'DAY_20220309': 'CA',
      'DAY_20220310': 'CA',
      'DAY_20220311': 'CA',
      'DAY_20220312': 'CA',
      'DAY_20220313': 'CA',
      'DAY_20220314': 'CA',
      'DAY_20220315': 'CA',
      'DAY_20220316': 'CA',
      'DAY_20220317': 'CA',
      'DAY_20220318': 'CA',
      'DAY_20220319': 'CA',
      'DAY_20220320': 'CA',
      'DAY_20220321': 'CA',
      'DAY_20220322': 'CA',
      'DAY_20220323': 'CA',
      'DAY_20220324': 'CA',
      'DAY_20220325': 'CA',
      'DAY_20220326': 'CA',
      'DAY_20220327': 'CA',
      'DAY_20220328': 'CA',
      'DAY_20220329': 'CA',
      'DAY_20220330': 'CA',
      "FULL_STYLEDAY_20220301": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
      "FULL_STYLEDAY_20220302": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
      "FULL_STYLEDAY_20220303": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
      "FULL_STYLEDAY_20220305": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220306": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220307": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220308": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220309": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220310": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220311": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220312": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220313": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220314": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220315": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220316": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220317": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220318": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220319": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220320": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220321": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220322": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220323": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220324": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220325": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220326": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220327": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220328": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220329": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px, white-space:nowrap,}",
      "FULL_STYLEDAY_20220330": "{background-image:url(../../assets/images/icons/GA_CA_RE_BONI.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      isGroup: true
  },
  {
      'TEAM_CODE': "14078009",
      'TEAM_LABEL': "BAYEUX EQ 1 (BAYEUX PDC1 > (HRLCD) BAYEUX PDC2)",
      'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC2",
      'ZEYDMETIER_Label': "FACTEUR",
      'ZEYDMETIER_Sort': 129,
      'ZEYDTYPEPA_Label': "PTR",
      'ZY00MATCLE': "TMP78904",
      'ZY00SOCCLE': "LPC",
      'ZY3YNMPRES': "TMPNOM TMPPRENOM",
      'ZY54TEMVHI': false,
      'ZY78IDAFFA': "1407803M",
      'ZY78IDAFFA_Label': "1006",
      'ZYCOTYPCON_Label': "CDD",
      "FULL_STYLEDAY_20220303": "{backgroundImage: url(../../assets/images/icons/sans_PA_exp.png), backgroundSize:40%,backgroundPosition:center center,backgroundRepeat:no-repeat,borderBottom:1px solid #A0A0A0,borderTop:1px solid #A0A0A0,borderRight:1px solid #A0A0A0,color:black,fontFamily:Arial,fontSize:10px !important, height:10px, width:10px}",
      "FULL_STYLEDAY_20220304": "{backgroundImage: url(../../assets/images/icons/sans_PA_exp.png), backgroundSize:40%,backgroundPosition:center center,backgroundRepeat:no-repeat,borderBottom:1px solid #A0A0A0,borderTop:1px solid #A0A0A0,borderRight:1px solid #A0A0A0,color:black,fontFamily:Arial,fontSize:10px !important, height:10px, width:10px}",
      "FULL_STYLEDAY_20220305": "{backgroundImage: url(../../assets/images/icons/sans_PA_exp.png), backgroundSize:40%,backgroundPosition:center center,backgroundRepeat:no-repeat,borderBottom:1px solid #A0A0A0,borderTop:1px solid #A0A0A0,borderRight:1px solid #A0A0A0,color:black,fontFamily:Arial,fontSize:10px !important, height:10px, width:10px}",
      "FULL_STYLEDAY_20220306": "{background-image:url(../../assets/images/icons/GA_PUBLIC_HOLIDAY.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px}",
      "FULL_STYLEDAY_20220307": "{background-image:url(../../assets/images/icons/GA_PUBLIC_HOLIDAY.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220308": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220309": "{backgroundImage: url(../../assets/images/icons/sans_PA_exp.png), backgroundSize:40%,backgroundPosition:center center,backgroundRepeat:no-repeat,borderBottom:1px solid #A0A0A0,borderTop:1px solid #A0A0A0,borderRight:1px solid #A0A0A0,color:black,fontFamily:Arial,fontSize:10px !important, height:10px, width:10px}",
      isGroup: true
  },
  { 'TEAM_CODE': "14078010", 'TEAM_LABEL': "BAYEUX EQ 1 (BAYEUX PDC1 > (HRLCD) BAYEUX PDC2)", 'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC2", 'ZEYDMETIER_Label': "FACTEUR", 'ZEYDMETIER_Sort': 129, 'ZEYDTYPEPA_Label': "PTR", 'ZY00MATCLE': "MVB294", 'ZY00SOCCLE': "LPC", 'ZY3YNMPRES': "MVBNOM MVBPRENOM", 'ZY54TEMVHI': false, 'ZY78IDAFFA': "1407803P", 'ZY78IDAFFA_Label': "1009", 'ZYCOTYPCON_Label': "CDI droit privé",
    "FULL_STYLEDAY_20220301": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220302": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220303": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220304": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220305": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220306": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220307": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220308": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220309": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220310": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220311": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220312": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220313": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220314": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220315": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220316": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220317": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220318": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220319": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220320": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220321": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220322": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220323": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220324": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220325": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220326": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220327": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220328": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220329": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    "FULL_STYLEDAY_20220330": "{background-image:url(../../assets/images/icons/GA_VARIOUS_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
    
     isGroup: true },
  {
      'TEAM_CODE': "14078011",
      'TEAM_LABEL': "BAYEUX EQ 1 (BAYEUX PDC1 > (HRLCD) BAYEUX PDC2)",
      'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC2",
      'ZEYDMETIER_Label': "FACTEUR",
      'ZEYDMETIER_Sort': 129,
      'ZEYDTYPEPA_Label': "PTR",
      'ZY00MATCLE': "",
      'ZY00SOCCLE': "",
      'ZY3YNMPRES': "",
      'ZY54TEMVHI': false,
      'ZY78IDAFFA': "1407803U",
      'ZY78IDAFFA_Label': "2011 F",
      'ZYCOTYPCON_Label': "CDD",
      "FULL_STYLEDAY_20220301": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220302": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220303": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220304": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220305": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220306": "{background-image:url(../../assets/images/icons/GA_PUBLIC_HOLIDAY.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important,height:22px}",
      "FULL_STYLEDAY_20220307": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220308": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220309": "{backgroundImage: url(../../assets/images/icons/sans_PA_exp.png), backgroundSize:40%,backgroundPosition:center center,backgroundRepeat:no-repeat,borderBottom:1px solid #A0A0A0,borderTop:1px solid #A0A0A0,borderRight:1px solid #A0A0A0,color:black,fontFamily:Arial,fontSize:10px !important, height:10px, width:10px}",
      isGroup: true
  },
  { 'TEAM_CODE': "14078012", 'TEAM_LABEL': "BAYEUX EQ 1 (BAYEUX PDC1 > (HRLCD) BAYEUX PDC2)", 'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC2", 'ZEYDMETIER_Label': "FACTEUR", 'ZEYDMETIER_Sort': 129, 'ZEYDTYPEPA_Label': "PTR", 'ZY00MATCLE': "MVB295", 'ZY00SOCCLE': "LPC", 'ZY3YNMPRES': "MVBNOM MVBPRENOM", 'ZY54TEMVHI': false, 'ZY78IDAFFA': "1407803P", 'ZY78IDAFFA_Label': "1010", 'ZYCOTYPCON_Label': "CDI droit privé", 
  "FULL_STYLEDAY_20220301": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220302": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220303": "{background-image:url(../../assets/images/icons/GA_REST.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
  "FULL_STYLEDAY_20220304": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220305": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220306": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220307": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220308": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220309": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220310": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220311": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220312": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220313": "{background-image:url(../../assets/images/icons/GA_REST.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
  "FULL_STYLEDAY_20220314": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220315": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220316": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220317": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220318": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220319": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220320": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220321": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220322": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220323": "{background-image:url(../../assets/images/icons/GA_REST.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
  "FULL_STYLEDAY_20220324": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220325": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220326": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220327": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220328": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220329": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  "FULL_STYLEDAY_20220330": "{background-image:url(../../assets/images/icons/sans_affectation.png), background-size:40%, background-position:center center, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, color:black, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,}",
  isGroup: true },
  {
      'TEAM_CODE': "14078013",
      'TEAM_LABEL': "BAYEUX EQ 1 (BAYEUX PDC1 > (HRLCD) BAYEUX PDC1)",
      'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC1",
      'ZEYDMETIER_Label': "FACTEUR",
      'ZEYDMETIER_Sort': 129,
      'ZEYDTYPEPA_Label': "PTR",
      'ZY00MATCLE': "AUZ428",
      'ZY00SOCCLE': "LPC",
      'ZY3YNMPRES': "AUZNOM AUZPRENOM",
      'ZY54TEMVHI': false,
      'ZY78IDAFFA': "1407803K",
      'ZY78IDAFFA_Label': "1004",
      'ZYCOTYPCON_Label': "CDI droit privé",
      "FULL_STYLEDAY_20220301": "{background-image:url(../../assets/images/icons/GA_REST.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220302": "{background-image:url(../../assets/images/icons/secabilite.png), background-size:15%, background-position:right bottom, background-repeat:no-repeat, border-bottom:1px solid #A0A0A0, border-top:1px solid white, border-right:1px solid #A0A0A0, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      "FULL_STYLEDAY_20220303": "{background-image:url(../../assets/images/icons/GA_REST.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,  }",
      "FULL_STYLEDAY_20220304": "{background-image:url(../../assets/images/icons/GA_REST.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,  }",
      "FULL_STYLEDAY_20220309": "{background-image:url(../../assets/images/icons/GA_REST.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px,  }",
      "FULL_STYLEDAY_20220305": "{background-image:url(../../assets/images/icons/GA_INACTIVE_LINE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, }",
      isGroup: true
  },
  {
      'TEAM_CODE': "140780FY",
      'TEAM_LABEL': "zTPAS (CODIR > BAYEUX PDC1 > (HRLCD) BAYEUX PDC1)",
      'TEAM_PARENT_LABEL': "(HRLCD) BAYEUX PDC1 > BAYEUX PDC1 > CODIR",
      'ZEYDMETIER_Label': "FACTEUR",
      'ZEYDMETIER_Sort': 129,
      'ZEYDTYPEPA_Label': "Hors Cref",
      'ZY00MATCLE': "FAY374",
      'ZY00SOCCLE': "LPC",
      'ZY3YNMPRES': "FAYNOM FAYPRENOM",
      'ZY54TEMVHI': false,
      'ZY78IDAFFA': "140780G4",
      'ZY78IDAFFA_Label': "TANQUE",
      'ZYCOTYPCON_Label': "CDI droit privé",
      "FULL_STYLEDAY_20220301": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220302": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220303": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220304": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220305": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220306": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220307": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220308": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220309": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220310": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220311": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220312": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220313": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220314": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220315": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220316": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220317": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220318": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220319": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220320": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220321": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220322": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220323": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220324": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220325": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220326": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220327": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220328": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220329": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      "FULL_STYLEDAY_20220330": "{background-image:url(../../assets/images/icons/GA_OTHER_ABSENCE.png), background-size:100%, background-position:center center, background-repeat:, border-bottom:1px solid #A0A0A0, border-top:1px solid #B8B8B8, border-right:1px solid #A0A0A0, color:white, font-family:Arial,Verdana,sans-serif, font-size:10px !important, height:22px, text-align:center,}",
      'DAY_20220301': 'AUT',
      'DAY_20220302': 'AUT',
      'DAY_20220303': 'AUT',
      'DAY_20220304': 'AUT',
      'DAY_20220305': 'AUT',
      'DAY_20220306': 'AUT',
      'DAY_20220307': 'AUT',
      'DAY_20220308': 'AUT',
      'DAY_20220309': 'AUT',
      'DAY_20220310': 'AUT',
      'DAY_20220311': 'AUT',
      'DAY_20220312': 'AUT',
      'DAY_20220313': 'AUT',
      'DAY_20220314': 'AUT',
      'DAY_20220315': 'AUT',
      'DAY_20220316': 'AUT',
      'DAY_20220317': 'AUT',
      'DAY_20220318': 'AUT',
      'DAY_20220319': 'AUT',
      'DAY_20220320': 'AUT',
      'DAY_20220321': 'AUT',
      'DAY_20220322': 'AUT',
      'DAY_20220323': 'AUT',
      'DAY_20220324': 'AUT',
      'DAY_20220325': 'AUT',
      'DAY_20220326': 'AUT',
      'DAY_20220327': 'AUT',
      'DAY_20220328': 'AUT',
      'DAY_20220329': 'AUT',
      'DAY_20220330': 'AUT',
      isGroup: true
  }, 

];

@Injectable({
  providedIn: 'root'
})
export class PlanningService {

  constructor() { }

  getListGridFields () {
    return listGridFields;
  }

  getDataElement () {
    // To return simple emlent data
    return dataElement;
  }

  getDataElementGlobal () {
    // to return a global data for testing performance
    const planningData = new PlanningData();
    return planningData.getDataElementGlobal();
  }

  getListOfDisplayColumns() {
    const displayedColumns: string[] = []
    for (let i=0; i <listGridFields.length; i++) {
      let fields = listGridFields[i];
      displayedColumns.push(fields.name);
    }
    return displayedColumns;
  }

}
